version: '3'
services:
  server:
    image: ghcr.io/fourdollars/playit-bedrock
    command: /opt/bedrock/bedrock_server
#     ports: [19132:19132/udp]
    stdin_open: true
    tty: true
    volumes:
      - ./worlds:/opt/bedrock/worlds
#       - ./server.properties:/opt/bedrock/server.properties
  playit:
    image: ghcr.io/fourdollars/playit-bedrock
    command: playit
    stdin_open: true
    tty: true
    network_mode: service:server
    volumes:
      - ./etc/playit:/etc/playit
