version: '3'
services:
  bedrock:
    container_name: bedrock
    image: ghcr.io/fourdollars/playit-bedrock
    command: /opt/bedrock/bedrock_server
#     ports: [19132:19132/udp]
    stdin_open: true
    tty: true
    volumes:
      - ./worlds:/opt/bedrock/worlds
#       - ./server.properties:/opt/bedrock/server.properties
  playit:
    container_name: playit
    restart: unless-stopped
    image: ghcr.io/fourdollars/playit-bedrock
    command: playit
    stdin_open: true
    tty: true
    volumes:
      - ./etc/playit:/etc/playit
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#       - $HOME/.docker/config.json:/config.json
    command: --cleanup --interval 60 --rolling-restart --stop-timeout 30s bedrock
